/*
 *  infer.c -- generate definitions reflecting present hardware architecture
 *
 *  Inspired by mail from Christian Hudon.
 */

#include <assert.h>
#include <stddef.h>
#include <stdio.h>

typedef unsigned int DIGIT;

typedef struct {
   char c;
   double d;
   } tstruct;

#pragma clang diagnostic ignored "-Wreturn-stack-address"
static long atdepth(int n) {
   return n <= 1 ? (long)&n : atdepth(n - 1);
   }

int main(int argc, char *argv[]) {
   int IntBits = 8 * sizeof(int);
   int WordBits = 8 * sizeof(void*);
   int NB;
   int wordlen;
   DIGIT maxint;
   NB = WordBits / 2;
   wordlen = WordBits / NB + (WordBits % NB != 0);
   maxint = 1 << ((WordBits - 1) % NB);
   assert (-1 == (signed char)0xFF);		/* chars must be 8 bits */
   assert (sizeof(void*) == sizeof(long));	/* these must be the same */
   assert (sizeof(int) >= 4);			/* need 32-bit ints or better */
   assert (sizeof(long) <= 8);			/* but can't handle over 64 */
   printf("/* generated by infer.c */\n");
   printf("#define IntBits %d\n", IntBits);
   printf("#define WordBits %d\n", WordBits);
   if (offsetof(tstruct, d) > sizeof(void *))
      printf("#define Double\n");
   if (atdepth(2) > atdepth(1))
      printf("#define UpStack\n");
   printf("#define WORDLEN %d\n", wordlen);
   printf("#define MAXWORD_0 ((DIGIT)%u)\n", (unsigned int)maxint);
   return 0;
   }
